--------------------------------------------------------
--  DDL for Table B_APP_CHILDREN
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_APP_CHILDREN" 
   (	"ACH_CODE" NUMBER(*,0), 
	"ACH_TABLE" VARCHAR2(20 BYTE), 
	"ACH_VIEW_TYPE" VARCHAR2(20 BYTE), 
	"ACH_ACO_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHILDREN"."ACH_CODE" IS 'Primary Key';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHILDREN"."ACH_TABLE" IS 'Child table name';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHILDREN"."ACH_VIEW_TYPE" IS 'View type of the child';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHILDREN"."ACH_ACO_CODE" IS 'Reference to the controller to which the child belongs to.';
